## Importing the Packages

In [192]:
import numpy as np

In [193]:
np.set_printoptions(suppress = True, linewidth= 100, precision = 2)

## Importing the Dataset

In [194]:
# delimiter=';': Specifies the delimiter
#skip_header=1: Skips the first row of the CSV file
#autostrip=True: Trims leading and trailing whitespaces from the loaded data

raw_data = np.genfromtxt('loan-data.csv',
                         delimiter =';',
                         skip_header = 1,
                         autostrip = True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [195]:
np.isnan(raw_data).sum()

88005

In [196]:
#temporary fill finds the maximum value in the array (raw_data) and adds 1 to it
temporary_fill = np.nanmax(raw_data) + 1

#Computes the mean values of the raw_data array along the columns, excluding NaN values.
temporary_mean = np.nanmean(raw_data, axis = 0)   

C:\Users\foyez\AppData\Local\Temp\ipykernel_10376\1743576735.py:5: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis = 0)


In [197]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [198]:
#The temporary_stat store the calculated statistics (minimum, mean, and maximum)
temporary_stat = np.array([np.nanmin(raw_data, axis = 0),
                          temporary_mean,
                          np.nanmax(raw_data, axis = 0)])

C:\Users\foyez\AppData\Local\Temp\ipykernel_10376\585169560.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stat = np.array([np.nanmin(raw_data, axis = 0),
C:\Users\foyez\AppData\Local\Temp\ipykernel_10376\585169560.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis = 0)])


In [199]:
temporary_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the columns

In [200]:
#column_strings: An array containing the indices (column) of NaN values within the temporary_mean array.
column_strings = np.argwhere(np.isnan(temporary_mean))
column_strings

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

In [201]:
#The squeeze() function is then applied to remove any unnecessary dimensions and obtain a 1-dimensional array.
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [202]:
# Columns that only contain numeric value
column_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [203]:
#array containing string data loaded from the specified columns of the CSV file.
#usecols=column_strings: Specifies the columns to be loaded.

loan_data_strings = np.genfromtxt('loan-data.csv',
                                 delimiter= ';',
                                 skip_header= 1,
                                 autostrip= True,
                                 usecols= column_strings,
                                 dtype = str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [204]:
#array containing numeric data loaded from the specified columns of the CSV file.


loan_data_numeric = np.genfromtxt('loan-data.csv',
                                 delimiter= ';',
                                 skip_header= 1,
                                 autostrip= True,
                                 usecols= column_numeric,
                                 filling_values= temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Name of the Columns

In [205]:
# header_all stores all the columns name
# skip_footer= raw_data.shape[0]: ignore all the rows except 1st one

header_all = np.genfromtxt('loan-data.csv',
                                 delimiter= ';',
                                 skip_footer = raw_data.shape[0],
                                 autostrip= True,
                                 dtype = str)
header_all

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [206]:
header_strings, header_numeric = header_all[column_strings], header_all[column_numeric]

In [207]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [208]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Creating the Checkpoints

In [209]:
#checkpoint function, which saves data and headers into a NumPy .npz file and returns the loaded checkpoint variable.

def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + '.npz')
    return (checkpoint_variable)

In [210]:
checkpoint_test = checkpoint('checkpoint_test', header_strings, loan_data_strings)

In [211]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [212]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [213]:
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

## Manipulating String Columns

In [214]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [215]:
header_strings[0] = 'issue_date'

In [216]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [217]:
#loan_data_strings array to retrieve all rows (:), but only the first column (0).
loan_data_strings[:, 0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [218]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [219]:
#np.chararray.strip() function is designed to remove leading and trailing characters from string arrays
#In this case, it is used to remove the characters '-15' from each element of the first column.

loan_data_strings[:, 0] = np.chararray.strip(loan_data_strings[:, 0], '-15')

In [220]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [221]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',])

In [222]:
# repalcing the months name into integer with the help of np.where() function
for i in range(13):
    loan_data_strings[:, 0] = np.where(loan_data_strings[:, 0] == months[i],
                                      i,
                                      loan_data_strings[:, 0])
    

In [223]:
np.unique(loan_data_strings[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [224]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [225]:
np.unique(loan_data_strings[:, 1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [226]:
np.unique(loan_data_strings[:, 1]).size

9

In [227]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [228]:
# replacing the loan_status column with 0 or 1 where 0 = bad, 1 = good
# The np.isin() function is used to check if each element in the second column is present in the status_bad array
# If an element is found in status_bad, the corresponding element in the second column is replaced with 0
# If an element is not found in status_bad, the element is replaced with 1

loan_data_strings[:, 1] = np.where(np.isin(loan_data_strings[:, 1], status_bad), 0, 1)

In [229]:
np.unique(loan_data_strings[:, 1])

array(['0', '1'], dtype='<U69')

### Term

In [230]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [231]:
np.unique(loan_data_strings[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [232]:
loan_data_strings[:, 2] = np.chararray.strip(loan_data_strings[:, 2], ' months')
loan_data_strings[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [233]:
header_strings[2] = 'term_months'
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [234]:
# replacing the empty term with worst case scenario '60' months
loan_data_strings[:, 2] = np.where(loan_data_strings[:, 2] == '',
                                  '60',
                                  loan_data_strings[:, 2])

In [235]:
np.unique(loan_data_strings[:, 2])

array(['36', '60'], dtype='<U69')

### Grade and Sub-grade

In [236]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [237]:
np.unique(loan_data_strings[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [238]:
np.unique(loan_data_strings[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling the Sub-grade

In [239]:
# replacing all the missing subgrade with corresponding garde+'5' value
for i in np.unique(loan_data_strings[:, 3])[1:]:
    loan_data_strings[:, 4] = np.where((loan_data_strings[:, 4] == '') & (loan_data_strings[:, 3] == i),
                                      i + '5',
                                      loan_data_strings[:, 4])

In [240]:
np.unique(loan_data_strings[:, 4], return_counts= True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [241]:
# replacing all the still missing sub-grade with imaginary 'H1' sub-grade 
loan_data_strings[:, 4] = np.where(loan_data_strings[:, 4] == '',
                                    'H1',
                                    loan_data_strings[:, 4])

In [242]:
np.unique(loan_data_strings[:, 4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing the Grade

In [243]:
#deletes the fourth column (index 3) from the loan_data_strings array using the np.delete() function from NumPy
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)

In [244]:
loan_data_strings[:, 3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [245]:
# deletes the grade column from header_columns
header_strings = np.delete(header_strings, 3)
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Converting the Sub-grade

In [246]:
np.unique(loan_data_strings[:, 3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [247]:
# construct a dictionary for subgrade values for 'A1' to 'H1' from 1 to 36
keys = list(np.unique(loan_data_strings[:, 3]))
values = list(range(1, np.unique(loan_data_strings[:, 3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [248]:
# replacing all the sub-grade with numeric values from previously contructed dictionary
for i in np.unique(loan_data_strings[:, 3]):
    loan_data_strings[:, 3] = np.where(loan_data_strings[:, 3] == i,
                                      dict_sub_grade[i],
                                      loan_data_strings[:, 3])
    
    


In [249]:
np.unique(loan_data_strings[:, 3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [250]:
header_strings


array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [251]:
np.unique(loan_data_strings[:, 4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [252]:
# replacing missing and 'not verified' field with 0 and verified with 1
loan_data_strings[:, 4] = np.where((loan_data_strings[:, 4] == '') | (loan_data_strings[:, 4] == 'Not Verified'),
                                  0, 1)

In [253]:
np.unique(loan_data_strings[:, 4])

array(['0', '1'], dtype='<U69')

### URL

In [254]:
np.unique(loan_data_strings[:, 5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [255]:
np.chararray.strip(loan_data_strings[:, 5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [256]:
# from 'URL' only keeping the numeric part 
loan_data_strings[:, 5] = np.chararray.strip(loan_data_strings[:, 5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [257]:
header_all

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [258]:
loan_data_numeric[:, 0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [259]:
loan_data_strings[:, 5].astype(dtype= np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [260]:
loan_data_numeric[:, 0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [261]:
np.array_equal(loan_data_strings[:, 5].astype(dtype= np.int32), loan_data_numeric[:, 0].astype(dtype=np.int32))

True

In [262]:
# removing 'URL' column from both data and header 
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [263]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [264]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

### State Address

In [265]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [266]:
header_strings[5] = 'state_address'

In [267]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [268]:
loan_data_strings[:, 5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [269]:
np.unique(loan_data_strings[:, 5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [270]:
np.unique(loan_data_strings[:, 5]).size

50

In [271]:
np.unique(loan_data_strings[:, 5], return_counts= True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [272]:
states_name, states_count = np.unique(loan_data_strings[:, 5], return_counts= True)

In [273]:
states_name

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [274]:
states_count

array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
         84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
        341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
         17,  216,  148,   49,   27], dtype=int64)

In [275]:
# argsort() returnsan array of indices that would sort the states_count array in ascending order
np.argsort(states_count)

array([20, 27, 45, 40, 28,  1, 49,  8,  9, 25, 38, 12, 48, 31, 29, 24, 43,  3, 35, 16, 15, 39, 36,
       17,  2, 32,  7, 41, 47, 14, 22, 23,  6, 18, 46,  4, 19, 44, 26, 21, 34, 37, 11, 30, 13,  0,
       10, 42, 33,  5], dtype=int64)

In [276]:
# (-) sign makes the array in descending order
states_count_sorted = np.argsort(-states_count)

In [277]:
states_name[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [278]:
#replacing with 0 in missing state address
loan_data_strings[:, 5] = np.where(loan_data_strings[:, 5] == '',
                                  0, loan_data_strings[:, 5])

In [279]:
# replacing the states name with categories
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [280]:
# replacing the states name in dataset with numeric categories
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_west), 1, loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_south), 2, loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_midwest), 3, loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_east), 4, loan_data_strings[:, 5])

In [281]:
np.unique(loan_data_strings[:, 5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting the String Dataset

In [282]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [283]:
loan_data_strings.astype(dtype = int)

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [284]:
loan_data_strings = loan_data_strings.astype(dtype = int)
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Checkpoint 1: String Data

In [285]:
# creating checkpoint for loan data strings 
checkpoint_strings = checkpoint('Checkpoint_Strings', header_strings, loan_data_strings)

In [286]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [287]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [288]:
np.array_equal(checkpoint_strings['data'], loan_data_strings)

True

## Manipulating Numeric Columns

In [289]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [290]:
np.isnan(loan_data_numeric).sum()

0

### Substitute the "Filler" Values

In [291]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [292]:
temporary_fill

68616520.0

In [293]:
np.isin(loan_data_numeric[:, 0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [294]:
np.isin(loan_data_numeric[:, 0], temporary_fill).sum()

0

#### Temporary Stats

In [295]:
temporary_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [296]:
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [297]:
# display the numeric column values
# 1st row = min, 2nd row = mean and 3rd row = max
temporary_stat[:, column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [298]:
loan_data_numeric[:, 2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [299]:
# using the column numeric indices substitite filling values with min 
loan_data_numeric[:, 2] = np.where(loan_data_numeric[:, 2] == temporary_fill,
                                  temporary_stat[0, column_numeric[2]],
                                  loan_data_numeric[:, 2])
loan_data_numeric[:, 2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loan Amount, Interest Rate, Total Payment, Installment

In [300]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [301]:
# subtitute the filler value with max value from temporary_stat
for i in [1, 3, 4, 5]:
    loan_data_numeric[:, i] = np.where(loan_data_numeric[:, i] == temporary_fill,
                                      temporary_stat[2, column_numeric[i]],
                                      loan_data_numeric[:, i]) 

In [302]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### Exchange Rate

In [303]:
EUR_USD = np.genfromtxt('EUR-USD.csv',
                        delimiter= ',',
                        autostrip= True,
                        skip_header= 1,
                        usecols= 3)

In [304]:
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [305]:
# loan_data_strings 1st column contanins all the months in numeric form
loan_data_strings[:, 0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [306]:
exchange_rate = loan_data_strings[:, 0]

In [307]:
# substituting the month value with that month exchange rate

for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i,
                            EUR_USD[i-1],
                            exchange_rate)
    
# substituting the 0 month value with that mean month exchange rate 

exchange_rate = np.where(exchange_rate == 0,
                        np.mean(EUR_USD),
                        exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [308]:
exchange_rate.shape

(10000,)

In [309]:
loan_data_numeric.shape

(10000, 6)

In [310]:
# making the exchange_rate shape 2d
exchange_rate = np.reshape(exchange_rate, (10000, 1))
exchange_rate.shape

(10000, 1)

In [311]:
# add exchange_rate to loan_data_numeric dataset
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [312]:
# adding to the header for newly added column to the dataset
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### USD to EURO

In [313]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [314]:
columns_dollar = np.array([1, 2, 4, 5])

In [315]:
loan_data_numeric[:, 6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [316]:
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000, 1))))

In [317]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [318]:
loan_data_numeric.shape

(10000, 11)

### Expanding the Header

In [320]:
header_additional = np.array([column_name + '_EURO' for column_name in header_numeric[columns_dollar]])
header_additional

array(['loan_amnt_EURO', 'funded_amnt_EURO', 'installment_EURO', 'total_pymnt_EURO'], dtype='<U16')

In [322]:
header_numeric = np.concatenate((header_numeric, header_additional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EURO', 'funded_amnt_EURO', 'installment_EURO', 'total_pymnt_EURO'], dtype='<U19')

In [323]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EURO', 'funded_amnt_EURO', 'installment_EURO',
       'total_pymnt_EURO'], dtype='<U19')

In [324]:
column_index_order = [0, 1, 7, 2, 8, 3, 4, 9, 5, 10, 6]

In [326]:
# Reorganizing the header_numeric 
header_numeric = header_numeric[column_index_order]
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EURO', 'funded_amnt_USD', 'funded_amnt_EURO', 'int_rate',
       'installment_USD', 'installment_EURO', 'total_pymnt_USD', 'total_pymnt_EURO',
       'exchange_rate'], dtype='<U19')

In [327]:
header_numeric.size

11

In [328]:
loan_data_numeric = loan_data_numeric[:, column_index_order]

In [329]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate